In [3]:
#basic merging

import pandas as pd
df1 = pd.DataFrame({
    "id":[1,2,3],
    "name":["asha","binu","cathy"]
})
df2 = pd.DataFrame({
    "id":[1,2,4],
    "mark":[85,90,75]
})

merged_df = pd.merge(df1,df2,on="id") 
merged_df

   id  name  mark
0   1  asha    85
1   2  binu    90

#TYPES OF MERGING(INNER,RIGHT,LEFT,OUTER)

In [4]:
#INNER MERGING
pd.merge(df1,df2,on="id",how = "inner")

   id  name  mark
0   1  asha    85
1   2  binu    90

In [5]:
#LEFT MERGE
pd.merge(df1,df2,on ="id",how = "left")

   id   name  mark
0   1   asha  85.0
1   2   binu  90.0
2   3  cathy   NaN

In [7]:
#RIGHT MERGE
pd.merge(df1,df2,on="id",how= "right")

   id  name  mark
0   1  asha    85
1   2  binu    90
2   4   NaN    75

In [9]:
#OUTER MERGE
pd.merge(df1,df2,on= "id",how="outer")

   id   name  mark
0   1   asha  85.0
1   2   binu  90.0
2   3  cathy   NaN
3   4    NaN  75.0

#MERGE ON DIFFERNCE COLUMN NAMES

In [12]:
import pandas as pd
df1 = pd.DataFrame({
    "id":[1,2,3],
    "name":["asha","binu","cathy"]
})
df2 = pd.DataFrame({
    "student_id":[1,2,4],
    "mark":[85,90,75]
})
merged_df=pd.merge(df1,df2,left_on="id",right_on="student_id")
merged_df

   id  name  student_id  mark
0   1  asha           1    85
1   2  binu           2    90

In [13]:
#CONCATENATION (ROW WISE)
pd.concat([df1,df2],axis = 0)

    id   name  student_id  mark
0  1.0   asha         NaN   NaN
1  2.0   binu         NaN   NaN
2  3.0  cathy         NaN   NaN
0  NaN    NaN         1.0  85.0
1  NaN    NaN         2.0  90.0
2  NaN    NaN         4.0  75.0

In [14]:
pd.concat([df1,df2],axis = 1)

   id   name  student_id  mark
0   1   asha           1    85
1   2   binu           2    90
2   3  cathy           4    75

In [19]:
#APPLY
import pandas as pd
mark = pd.Series([45,60,70,80])
def grade(x):
   if x>50:
       return  "pass"
   else:
      return"fail"
mark.apply(grade)

0    fail
1    pass
2    pass
3    pass
dtype: object

In [22]:
#apply using lambda
mark.apply(lambda x:x+5)

0    50
1    65
2    75
3    85
dtype: int64

In [24]:
#apply on data frame columns
import pandas as pd
stud =pd.DataFrame({
    "maths":[10,20,30,40],
    "it":[50,60,70,12]
})
stud.apply(max)

maths    40
it       70
dtype: int64