In [16]:
import pandas as pd
df1=pd.DataFrame({
    "id":[1,2,3,4],
    "course":["ui/ux","data analyst","phython","c"],
    "Name":["rijo","sanju","aflah","vishnu"],
})
df2=pd.DataFrame({
    "id":[1,2,3,5],
    "mark":[20,40,80,60]
})
merged_df = pd.merge(df1,df2,on="id")
merged_df

   id        course   Name  mark
0   1         ui/ux   rijo    20
1   2  data analyst  sanju    40
2   3       phython  aflah    80

In [12]:
pd.merge(df1,df2,on="id",how="inner")

   id        course   Name  mark
0   1         ui/ux   rijo    20
1   2  data analyst  sanju    40
2   3       phython  aflah    80

In [13]:
pd.merge(df1,df2,on="id",how="left")

   id        course    Name  mark
0   1         ui/ux    rijo  20.0
1   2  data analyst   sanju  40.0
2   3       phython   aflah  80.0
3   4             c  vishnu   NaN

In [14]:
pd.merge(df1,df2,on="id",how="right")

   id        course   Name  mark
0   1         ui/ux   rijo    20
1   2  data analyst  sanju    40
2   3       phython  aflah    80
3   5           NaN    NaN    60

In [15]:
pd.merge(df1,df2,on="id",how="outer")

   id        course    Name  mark
0   1         ui/ux    rijo  20.0
1   2  data analyst   sanju  40.0
2   3       phython   aflah  80.0
3   4             c  vishnu   NaN
4   5           NaN     NaN  60.0

In [17]:
import pandas as pd
df1=pd.DataFrame({
    "student_id":[1,2,3,4],
    "course":["ui/ux","data analyst","phython","c"],
    "Name":["rijo","sanju","aflah","vishnu"],
})
df2=pd.DataFrame({
    "id":[1,2,3,5],
    "mark":[20,40,80,60]
})
merged_df = pd.merge(df1,df2,left_on="student_id",right_on="id")
merged_df

   student_id        course   Name  id  mark
0           1         ui/ux   rijo   1    20
1           2  data analyst  sanju   2    40
2           3       phython  aflah   3    80

In [18]:
pd.merge(df1,df2,left_on="student_id",right_on="id",how="inner")

   student_id        course   Name  id  mark
0           1         ui/ux   rijo   1    20
1           2  data analyst  sanju   2    40
2           3       phython  aflah   3    80

In [19]:
pd.merge(df1,df2,left_on="student_id",right_on="id",how="left")

   student_id        course    Name   id  mark
0           1         ui/ux    rijo  1.0  20.0
1           2  data analyst   sanju  2.0  40.0
2           3       phython   aflah  3.0  80.0
3           4             c  vishnu  NaN   NaN

In [20]:
pd.merge(df1,df2,left_on="student_id",right_on="id",how="right")

   student_id        course   Name  id  mark
0         1.0         ui/ux   rijo   1    20
1         2.0  data analyst  sanju   2    40
2         3.0       phython  aflah   3    80
3         NaN           NaN    NaN   5    60

In [21]:
pd.merge(df1,df2,left_on="student_id",right_on="id",how="outer")

   student_id        course    Name   id  mark
0         1.0         ui/ux    rijo  1.0  20.0
1         2.0  data analyst   sanju  2.0  40.0
2         3.0       phython   aflah  3.0  80.0
3         4.0             c  vishnu  NaN   NaN
4         NaN           NaN     NaN  5.0  60.0