In [2]:
import pandas as pd

data ={
    "name":["asha","rahul","anu"],
    "age":[20,21,19],
    "city":["kochi","delhi","chennai"]
}
df = pd.DataFrame(data)
df

    name  age     city
0   asha   20    kochi
1  rahul   21    delhi
2    anu   19  chennai

In [4]:
#selecting by label(loc)
df.loc[1]

name    rahul
age        21
city    delhi
Name: 1, dtype: object

In [6]:
df.loc[0:1,["name","age"]]

    name  age
0   asha   20
1  rahul   21

In [7]:
#selecting by position(intex)(iloc)
df.iloc[1]

name    rahul
age        21
city    delhi
Name: 1, dtype: object

In [8]:
df.iloc[0:2,0:2]

    name  age
0   asha   20
1  rahul   21

In [9]:
#DIFFERENCE IN SLICEING(ending included)
df.loc[0:1]

    name  age   city
0   asha   20  kochi
1  rahul   21  delhi

In [10]:
#(ending excluded)
df.iloc[0:1]

   name  age   city
0  asha   20  kochi

In [13]:
#SELECTING SINGLE VALUE
df.loc[2,"city"]

'chennai'

In [14]:
df.iloc[2,2]

'chennai'