In [115]:
#creating series
import pandas as pd
numbers=[10,20,30,40]
num_series= pd.Series(numbers)
num_series

0    10
1    20
2    30
3    40
dtype: int64

In [116]:
#with custom index
marks = [12,23,45,78]
mark_series = pd.Series(marks,index=["rijo","arun","rahul","aflah"])
mark_series

rijo     12
arun     23
rahul    45
aflah    78
dtype: int64

In [117]:
#CREATING SERIES WITH DIC
student ={
    "name":"rijo",
    "age":21,
    "place":"pariyapuram"
}
stud_d = pd.Series(student)
stud_d

name            rijo
age               21
place    pariyapuram
dtype: object

In [118]:
#accsessing with position
stud_d.iloc[0]

'rijo'

In [119]:
#accsessing with label
stud_d.loc["name"]

'rijo'

In [120]:
#printing all index values
stud_d.index

Index(['name', 'age', 'place'], dtype='object')

In [121]:
# data type
num_series.dtype

dtype('int64')

In [122]:
num_series.sum()

np.int64(100)

In [123]:
num_series.mean()

np.float64(25.0)

In [124]:
num_series.max()

40

In [125]:
num_series.min()

10

In [126]:
num_series.count()

np.int64(4)

In [127]:
# for printing the 1st 5 elements in the data
stud_d.head()

name            rijo
age               21
place    pariyapuram
dtype: object

In [128]:
#for printing the element by the index
stud_d.head(1)

name    rijo
dtype: object

In [129]:
# for printing the last 5 elements in the data
stud_d.tail()

name            rijo
age               21
place    pariyapuram
dtype: object

In [130]:
#for printing the element using index
stud_d.tail(2)

age               21
place    pariyapuram
dtype: object

In [131]:
#filitering data
da =pd.Series([10,20,30,40,50,60])
da[da > 30]

3    40
4    50
5    60
dtype: int64

In [132]:
#updating data
da[1]=100
da

0     10
1    100
2     30
3     40
4     50
5     60
dtype: int64

In [133]:
da["new"]=20
da

0       10
1      100
2       30
3       40
4       50
5       60
new     20
dtype: int64

In [134]:
da.drop("new")

0     10
1    100
2     30
3     40
4     50
5     60
dtype: int64

#DATA FRAME

In [135]:
import pandas as pd
stud ={
    "name":["aflah","vishnu","rijo","anadhu"],
     "age":[34,50,12,22],
     "course" :["UI/UX","phython","data analytics","C"]   
}
df = pd.DataFrame(stud)
df

     name  age          course
0   aflah   34           UI/UX
1  vishnu   50         phython
2    rijo   12  data analytics
3  anadhu   22               C

In [136]:
df.head()

     name  age          course
0   aflah   34           UI/UX
1  vishnu   50         phython
2    rijo   12  data analytics
3  anadhu   22               C

In [137]:
df.head(2)

     name  age   course
0   aflah   34    UI/UX
1  vishnu   50  phython

In [138]:
df.tail()

     name  age          course
0   aflah   34           UI/UX
1  vishnu   50         phython
2    rijo   12  data analytics
3  anadhu   22               C

In [139]:
df.tail(2)

     name  age          course
2    rijo   12  data analytics
3  anadhu   22               C

In [140]:
df.shape

(4, 3)

In [141]:
df.dtypes

name      object
age        int64
course    object
dtype: object

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   course  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [143]:
df.columns

Index(['name', 'age', 'course'], dtype='object')

In [144]:
df.describe()

             age
count   4.000000
mean   29.500000
std    16.360522
min    12.000000
25%    19.500000
50%    28.000000
75%    38.000000
max    50.000000

In [145]:
df[["name","course"]]

     name          course
0   aflah           UI/UX
1  vishnu         phython
2    rijo  data analytics
3  anadhu               C

In [146]:
df.loc[0]

name      aflah
age          34
course    UI/UX
Name: 0, dtype: object

In [147]:
df.iloc[1]

name       vishnu
age            50
course    phython
Name: 1, dtype: object

In [148]:
df["age"].sum()

np.int64(118)

In [149]:
df["age"].mean()

np.float64(29.5)

In [150]:
df["age"].max()

50

In [151]:
df["age"].min()

12

In [152]:
df["age"].count()

np.int64(4)

In [153]:
df[df["age"] > 45]

     name  age   course
1  vishnu   50  phython

In [154]:
df["palce"]=["pariyapuram","thrissur","kottayam","kannur"]
df

     name  age          course        palce
0   aflah   34           UI/UX  pariyapuram
1  vishnu   50         phython     thrissur
2    rijo   12  data analytics     kottayam
3  anadhu   22               C       kannur

In [155]:
df= df.drop("palce",axis = 1)

In [156]:
df

     name  age          course
0   aflah   34           UI/UX
1  vishnu   50         phython
2    rijo   12  data analytics
3  anadhu   22               C

In [162]:
df.to_csv("studentss.csv",index=False)